controller_manager:
  ros__parameters:
    update_rate: 50 # 50 Hz is fine for servo control

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - jrotate1
      - jlink1
      - jlink2
      - jrotate2
      - jend
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: true # Important for mock_components
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - jconnector
      - jsgear
      - jbutton1
      - jmconnector
      - jhorn
      - jmbutton1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_integration_in_goal_trajectories: true